<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <body>
        <div id="root">
            <!--creating a heading element using html-->
            <h1>welcome to react</h1>
        </div>
        <!--creating a heading element using html-->
        <h3>welcome to react</h3>
        <script>
            //creating javascript element h1
            var h1ele = document.createElement("h1");
            h1ele.innerHTML = "welcome to react";

            //fetching root element or container of the page
            var rootElement = document.getElementById("root");

            rootElement.appendChild(h1ele);
        </script>

        <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>

        <script>
            //creating react element using CDN links
            var h1elereact= React.createElement("h6",{},"welcome to react");
            var htmlRoot = document.getElementById("root");
            var rootReact = ReactDOM.createRoot(htmlRoot);
            rootReact.render(h1elereact);
        </script>

    </body>
</body>
</html>
